### ISSUE TITLE
People are missing from the Directory Database

### ISSUE THREAD

**Issue by stephensilber** [doubletissue/RPI-Directory#40]
I've implemented this app into RPI Mobile but recently I noticed there are a lot of people missing from the database. I've checked on the webapp as well (http://rpidirectory.appspot.com/) and get no results when searching myself and several others.

**Comment by christianjohnson** [comment]
Hello Stephen,

First off - thanks for using our API and letting us know about missing
people.  We moved over to a different backend and haven't finished crawling
the entire directory yet, but if you could let us know individual names
that are missing we'll take a look and see if there's a deeper issue going
on.

Thanks,
Christian

On Mon, Aug 20, 2012 at 2:05 PM, Stephen Silber notifications@github.comwrote:

> I've implemented this app into RPI Mobile but recently I noticed there are
> a lot of people missing from the database. I've checked on the webapp as
> well (http://rpidirectory.appspot.com/) and get no results when searching
> myself and several others.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jewishdan18/RPI-Directory/issues/40.

## 

Christian Johnson
www.christianjohnson.org
Notary Public
KB1VVD

**Comment by stephensilber** [comment]
Some individual names:
Stephen Silber
Jainesh Patel
Sean Hawthorne
Cheryl Tran
Sam Ellis

All of the above are juniors, but there may be some other categories that are missing.

**Comment by doubletissue** [comment]
All mentioned names are in the database
