### ISSUE TITLE
Android app real-time searching

### ISSUE THREAD

**Issue by wearable-bread** [doubletissue/RPI-Directory#7]
Search the database in "real-time". What I'm thinking of doing is waiting for the first 3 letters to be entered, then querying for all results that starts with those three letters, and pruning them on the phone as more letters are entered. If any of the first 3 are replaced, get the results again.

Problem: less than 3 letters entered. May have a button? Perhaps a delay after which it automatically starts.

**Comment by doubletissue** [comment]
use the same system as the web UI?

**Comment by doubletissue** [comment]
also, current api only does exact matches.  there is an issue to allow prefix searches

**Comment by doubletissue** [comment]
ok API now does prefix matching, so you should be good to go.

**Comment by wearable-bread** [comment]
Implemented
